# Generated by Django 4.2.16 on 2026-03-20 05:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
                ('original_file', models.FileField(blank=True, upload_to='originals/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('hls_path', models.CharField(blank=True, help_text='Relative path to m3u8 playlist inside MEDIA_ROOT', max_length=500)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Original file size in bytes', null=True)),
                ('resolution', models.CharField(blank=True, help_text='e.g. 1920x1080', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('views_count', models.PositiveBigIntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
