# Generated by Django 4.2.16 on 2026-03-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_channel_alter_video_duration_alter_video_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='available_qualities',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
