# Generated by Django 4.2.11 on 2026-04-01 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_phase4_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. English, Director's Commentary", max_length=100)),
                ('language', models.CharField(default='en', max_length=10)),
                ('track_index', models.IntegerField(default=0, help_text='Stream index in the source file')),
                ('hls_path', models.CharField(blank=True, help_text='Relative path to the HLS audio-only playlist', max_length=500)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_tracks', to='videos.video')),
            ],
            options={
                'ordering': ['-is_default', 'track_index'],
            },
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', help_text='BCP-47 code, e.g. en, fr, es', max_length=10)),
                ('language_label', models.CharField(default='English', max_length=60)),
                ('format', models.CharField(choices=[('vtt', 'WebVTT'), ('srt', 'SRT')], default='vtt', max_length=3)),
                ('file', models.FileField(upload_to='subtitles/')),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='videos.video')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('video', 'language', 'is_auto_generated')},
            },
        ),
    ]
