# Generated by Django 4.2.11 on 2026-04-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_phase5_celery_captions_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('text', models.TextField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='videos.video')),
            ],
            options={
                'ordering': ['start_seconds'],
                'indexes': [models.Index(fields=['video', 'start_seconds'], name='videos_vide_video_i_6b0646_idx')],
            },
        ),
    ]
