# Generated by Django 4.2.16 on 2026-04-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_add_face_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detectedface',
            new_name='videos_dete_video_i_8d7f48_idx',
            old_name='videos_dete_video_i_f9b3c2_idx',
        ),
        migrations.RenameIndex(
            model_name='detectedface',
            new_name='videos_dete_identit_8528a7_idx',
            old_name='videos_dete_identit_b7a1c3_idx',
        ),
        migrations.RenameIndex(
            model_name='videoframe',
            new_name='videos_vide_video_i_417b13_idx',
            old_name='videos_vide_video_i_frames_idx',
        ),
        migrations.AddField(
            model_name='videoframe',
            name='clip_embedding',
            field=models.TextField(blank=True, help_text='CLIP image embedding JSON (512-dim float list)'),
        ),
        migrations.AlterField(
            model_name='videoframe',
            name='description',
            field=models.TextField(blank=True, help_text='Natural language scene description (Phase C)'),
        ),
        migrations.AlterField(
            model_name='videoframe',
            name='face_count',
            field=models.IntegerField(default=0, help_text='Number of "person" detections in this frame'),
        ),
        migrations.AlterField(
            model_name='videoframe',
            name='face_names',
            field=models.TextField(blank=True, help_text='Comma-separated identified names (Phase B InsightFace)'),
        ),
        migrations.AlterField(
            model_name='videoframe',
            name='labels',
            field=models.TextField(blank=True, help_text='Comma-separated YOLO class labels, e.g. "person, car, dog"'),
        ),
    ]
