# Generated by Django 4.2.16 on 2026-04-02 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0013_userprofile_channel_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='editable_channels', to=settings.AUTH_USER_MODEL, verbose_name='Additional Editors'),
        ),
    ]
