# Generated by Django 4.2.16 on 2026-04-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_channel_editors'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='faceidentity',
            index=models.Index(fields=['name'], name='faceidentity_name'),
        ),
        migrations.AddIndex(
            model_name='faceidentity',
            index=models.Index(fields=['is_auto_named'], name='faceidentity_auto'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='notif_recipient'),
        ),
        migrations.AddIndex(
            model_name='savedvideo',
            index=models.Index(fields=['user', 'saved_at'], name='saved_user_time'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', 'visibility'], name='video_status_vis'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['channel', 'status', 'visibility'], name='video_ch_status_vis'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['category', 'status', 'visibility'], name='video_cat_status_vis'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['created_at'], name='video_created_at'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['views_count'], name='video_views'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['duration'], name='video_duration'),
        ),
        migrations.AddIndex(
            model_name='watchhistory',
            index=models.Index(fields=['user', 'watched_at'], name='watch_user_time'),
        ),
    ]
