# Generated by Django 4.2.16 on 2026-04-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_add_db_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='detectedface',
            index=models.Index(fields=['identity', 'status'], name='detface_identity_status'),
        ),
        migrations.AddIndex(
            model_name='detectedface',
            index=models.Index(fields=['identity', 'video'], name='detface_identity_video'),
        ),
    ]
