# Generated by Django 4.2.16 on 2026-04-06 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0021_photo_ocr_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='share_token',
            field=models.CharField(blank=True, help_text='Token for shareable public link', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='smart_filter',
            field=models.JSONField(blank=True, help_text='e.g. {"label":"dog"} or {"face":"Soham"}', null=True),
        ),
        migrations.AlterField(
            model_name='albumphoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
