# Generated by Django 4.2.16 on 2026-04-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_detectedface_photo_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detectedface',
            new_name='videos_dete_photo_i_0fcd4a_idx',
            old_name='videos_detec_photo_i_75b1c9_idx',
        ),
    ]
