# Generated by Django 4.2.16 on 2026-04-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0025_photo_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='exif_data',
            field=models.JSONField(blank=True, help_text='Camera EXIF metadata: make, model, GPS, exposure settings, etc.', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='taken_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date/time the photo was taken (from EXIF DateTimeOriginal)', null=True),
        ),
        migrations.AddField(
            model_name='videosegment',
            name='speaker_label',
            field=models.CharField(blank=True, help_text='Speaker label from diarization, e.g. SPEAKER_00', max_length=50),
        ),
    ]
