# Generated by Django 4.2.16 on 2026-04-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_add_speaker_label_and_exif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosegment',
            name='speaker_label',
            field=models.CharField(blank=True, help_text='Raw pyannote speaker label, e.g. SPEAKER_02', max_length=50),
        ),
        migrations.CreateModel(
            name='SpeakerIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_auto_named', models.BooleanField(default=True, help_text='True until owner gives this speaker a real name')),
                ('role', models.CharField(choices=[('speaker', 'Speaker'), ('narrator', 'Narrator'), ('background', 'Background')], default='speaker', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face_identity', models.ForeignKey(blank=True, help_text='Manually linked face identity — set by user to cross-reference voice + face', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_identities', to='videos.faceidentity')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='videosegment',
            name='speaker_identity',
            field=models.ForeignKey(blank=True, help_text='Resolved SpeakerIdentity — set after diarization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='videos.speakeridentity'),
        ),
        migrations.AddIndex(
            model_name='speakeridentity',
            index=models.Index(fields=['name'], name='speakerid_name'),
        ),
        migrations.AddIndex(
            model_name='speakeridentity',
            index=models.Index(fields=['is_auto_named'], name='speakerid_auto'),
        ),
        migrations.AddIndex(
            model_name='speakeridentity',
            index=models.Index(fields=['role'], name='speakerid_role'),
        ),
    ]
