# Generated by Django 4.2.16 on 2026-04-08 15:43

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_add_speaker_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakeridentity',
            name='speaker_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=256, help_text='Mean wespeaker-voxceleb-resnet34-LM embedding for cross-video matching', null=True),
        ),
    ]
