# Generated by Django 4.2.16 on 2026-04-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0028_add_speaker_embedding'),
    ]

    operations = [
        # HNSW index for ANN cosine search over speaker embeddings.
        # This accelerates cross-video speaker matching in run_diarization_task.
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS speaker_embedding_hnsw
                    ON videos_speakeridentity
                    USING hnsw (speaker_embedding vector_cosine_ops)
                    WITH (m = 16, ef_construction = 64);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS speaker_embedding_hnsw;
            """,
        ),
    ]

