# Generated by Django 4.2.16 on 2026-04-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0029_speaker_embedding_hnsw'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='videosegment',
            index=models.Index(fields=['speaker_identity', 'video', 'start_seconds'], name='videoseg_spk_vid_start'),
        ),
        migrations.AddIndex(
            model_name='videosegment',
            index=models.Index(fields=['speaker_identity'], name='videoseg_speaker'),
        ),
        migrations.AddIndex(
            model_name='detectedface',
            index=models.Index(fields=['video', 'identity', 'timestamp'], name='detface_vid_ident_ts'),
        ),
        migrations.CreateModel(
            name='SpeakerFaceSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='Higher = stronger evidence (overlap ratio vs speech).')),
                ('overlap_seconds', models.FloatField(default=0.0, help_text='Estimated speech/face overlap in seconds.')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Heuristic metadata for review.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('face_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_suggestions', to='videos.faceidentity')),
                ('speaker_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_suggestions', to='videos.speakeridentity')),
                ('video', models.ForeignKey(blank=True, help_text='Source video where this co-occurrence was observed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_face_suggestions', to='videos.video')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [
                    models.Index(fields=['speaker_identity', 'status'], name='spkfacesugg_spk_status'),
                    models.Index(fields=['face_identity', 'status'], name='spkfacesugg_face_status'),
                    models.Index(fields=['video'], name='spkfacesugg_video'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('speaker_identity', 'face_identity', 'video'), name='spk_face_suggestion_unique_triplet'),
                ],
            },
        ),
    ]
