# Generated by Django 4.2.16 on 2026-04-13 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0030_speakerfacesuggestion_and_segment_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(help_text='Start time in seconds')),
                ('end_timestamp', models.FloatField(blank=True, help_text='End time in seconds (optional)', null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('team', 'Team')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_moments', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='videos.video')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['video', 'visibility'], name='videos_vide_video_i_5b195a_idx'), models.Index(fields=['video', 'created_by'], name='videos_vide_video_i_5ceaf6_idx')],
            },
        ),
    ]
