# Generated by Django 4.2.16 on 2026-04-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0031_videomoment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomoment',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'None'), ('important', 'Important'), ('celebration', 'Celebration'), ('watch_again', 'Watch Again'), ('highlight', 'Highlight'), ('note', 'Note'), ('question', 'Question')], default='', max_length=20),
        ),
    ]
