# Generated by Django 4.2.16 on 2026-04-18 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0034_nicknames_and_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_categories', to='videos.channel')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('channel', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ChannelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_tags', to='videos.tagcategory')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_tags', to='videos.channel')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('channel', 'name')},
            },
        ),
    ]
