# Generated by Django 4.2.16 on 2026-04-18 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0035_tagcategory_channeltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomoment',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.CreateModel(
            name='MomentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='🏷️', max_length=8)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
