# Generated by Django 4.2.16 on 2026-04-19 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0036_moment_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tagcategory',
            name='channel',
        ),
        migrations.DeleteModel(
            name='ChannelTag',
        ),
        migrations.DeleteModel(
            name='TagCategory',
        ),
    ]
