# Generated by Django 4.2.16 on 2026-04-19 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0038_named_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='named_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.namedplace'),
        ),
    ]
