# Generated by Django 4.2.16 on 2026-04-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0039_video_named_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
