# Generated by Django 4.2.16 on 2026-04-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0040_video_lat_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
