# Generated by Django 4.2.16 on 2026-04-19 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0041_video_location_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, help_text='Snapshot of username at time of action', max_length=150)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('archive', 'Archive'), ('restore', 'Restore'), ('bulk', 'Bulk operation'), ('run_command', 'Run command'), ('role_change', 'Role change'), ('permission_change', 'Permission change'), ('regenerate', 'Regenerate'), ('tag', 'Tag'), ('merge', 'Merge'), ('rename', 'Rename'), ('other', 'Other')], default='other', max_length=32)),
                ('verb', models.CharField(blank=True, help_text='Short human-readable description, e.g. "uploaded video"', max_length=140)),
                ('target_type', models.CharField(blank=True, help_text='Model name of the target, e.g. "Video", "Photo"', max_length=64)),
                ('target_id', models.CharField(blank=True, help_text='PK of the target at time of action', max_length=64)),
                ('target_label', models.CharField(blank=True, help_text='Human-friendly identifier snapshot (title/name)', max_length=500)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{ field: {"before": ..., "after": ...}, ... }')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra free-form context')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('request_path', models.CharField(blank=True, max_length=500)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='act_ts_idx'), models.Index(fields=['actor', '-timestamp'], name='act_actor_ts_idx'), models.Index(fields=['target_type', 'target_id'], name='act_target_idx'), models.Index(fields=['action', '-timestamp'], name='act_action_ts_idx')],
            },
        ),
    ]
