# Generated by Django 4.2.16 on 2026-04-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0042_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upscaled_size',
            field=models.BigIntegerField(blank=True, help_text='Total size of all upscaled MP4 files in media/upscaled/<id>/ in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Size of the original uploaded file in bytes', null=True),
        ),
    ]
