# Generated by Django 4.2.16 on 2026-04-20 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0043_video_upscaled_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects', 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='photo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='If set, this photo is in Trash and hidden everywhere', null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='deleted_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='If set, this video is in Trash and hidden everywhere', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='video',
            name='deleted_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
