# Generated by Django 4.2.16 on 2026-04-23 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0044_alter_photo_options_alter_video_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField()),
                ('label', models.CharField(choices=[('silence', 'Silence'), ('applause', 'Applause'), ('laughter', 'Laughter'), ('music', 'Music'), ('cheering', 'Cheering'), ('crowd', 'Crowd noise'), ('booing', 'Booing'), ('speech', 'Speech')], max_length=32)),
                ('confidence', models.FloatField(default=0.0, help_text='Mean softmax probability for PANNs; 0.0 for FFmpeg-derived silence')),
                ('source', models.CharField(choices=[('panns', 'PANNs'), ('ffmpeg', 'FFmpeg silencedetect')], default='panns', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_events', to='videos.video')),
            ],
            options={
                'ordering': ['start_seconds'],
                'indexes': [models.Index(fields=['video', 'start_seconds'], name='videos_audi_video_i_ef66f5_idx'), models.Index(fields=['video', 'label'], name='videos_audi_video_i_138826_idx')],
            },
        ),
    ]
