# Generated by Django 4.2.16 on 2026-04-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0045_audioevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login failed'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('archive', 'Archive'), ('restore', 'Restore'), ('purge', 'Permanent delete (purge)'), ('bulk', 'Bulk operation'), ('run_command', 'Run command'), ('role_change', 'Role change'), ('permission_change', 'Permission change'), ('regenerate', 'Regenerate'), ('tag', 'Tag'), ('merge', 'Merge'), ('rename', 'Rename'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
