# Generated by Django 4.2.16 on 2026-05-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0046_alter_activitylog_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subtitle',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='is_translation',
            field=models.BooleanField(default=False, help_text='True if generated by NLLB translation, not direct transcription'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='source_language',
            field=models.CharField(blank=True, default='', help_text='BCP-47 code of the language this was translated from', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='subtitle',
            unique_together={('video', 'language', 'is_auto_generated', 'is_translation')},
        ),
    ]
