# Generated by Django 4.2.16 on 2026-05-13 05:23

from django.db import migrations, models
import django.db.models.deletion
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0047_add_subtitle_translation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=videos.models._generate_stream_key, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream_key', to='videos.channel')),
            ],
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended'), ('processing', 'Processing'), ('ready', 'Ready')], default='live', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('hls_path', models.CharField(blank=True, default='', help_text='Relative path to live.m3u8 inside MEDIA_ROOT', max_length=500)),
                ('recording_path', models.CharField(blank=True, default='', help_text='Relative path to recording.mp4 inside MEDIA_ROOT', max_length=500)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to='videos.channel')),
                ('stream_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.streamkey')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_live_stream', to='videos.video')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
