# Generated by Django 4.2.16 on 2026-05-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0048_add_livestream_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
