# Generated by Django 4.2.16 on 2026-05-14 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0049_add_video_ai_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable label, e.g. "LMS Integration"', max_length=120)),
                ('key_prefix', models.CharField(help_text='First 16 chars of raw key — for display only', max_length=20)),
                ('key_hash', models.CharField(db_index=True, help_text='SHA-256 of raw key', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='null = never expires', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIKeyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('search:global', 'Search — Global (entire library)'), ('search:channel', 'Search — Channel (scoped to one channel)'), ('search:playlist', 'Search — Playlist (scoped to one playlist)'), ('video:read', 'Video Read (metadata + transcript)'), ('video:upload', 'Video Upload (to a specific channel)')], max_length=30)),
                ('scope_id', models.CharField(blank=True, default='', help_text='UUID of the scoped channel/playlist, empty for global', max_length=40)),
                ('scope_name', models.CharField(blank=True, default='', help_text='Snapshot name for display (channel/playlist name)', max_length=200)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='videos.apikey')),
            ],
            options={
                'unique_together': {('api_key', 'permission', 'scope_id')},
            },
        ),
    ]
