# Generated by Django 4.2.16 on 2026-05-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0050_add_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_platform_owner',
            field=models.BooleanField(default=False),
        ),
    ]
