# Generated by Django 4.2.16 on 2026-06-03 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0051_add_is_platform_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='redacted_raw_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Redaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('face', 'Face (visual)'), ('voice', 'Voice (audio + transcript)'), ('region', 'Generic region'), ('audio_range', 'Audio range'), ('text', 'On-screen text')], max_length=20)),
                ('method', models.CharField(choices=[('blur', 'Blur'), ('pixelate', 'Pixelate'), ('black_box', 'Black box'), ('mute', 'Mute (silence)'), ('beep', 'Beep tone'), ('voice_change', 'Voice change (pitch shift)')], max_length=20)),
                ('severity', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='medium', max_length=10)),
                ('time_start_s', models.FloatField(default=0)),
                ('time_end_s', models.FloatField(default=0)),
                ('spatial_mode', models.CharField(choices=[('whole_frame', 'Whole frame'), ('fixed_box', 'Fixed box'), ('tracked_face', 'Tracks face detections')], default='fixed_box', max_length=20)),
                ('bbox_x', models.FloatField(default=0, help_text='0-1 from left')),
                ('bbox_y', models.FloatField(default=0, help_text='0-1 from top')),
                ('bbox_w', models.FloatField(default=0, help_text='0-1 width')),
                ('bbox_h', models.FloatField(default=0, help_text='0-1 height')),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('ai_face', 'From face detection'), ('ai_voice', 'From speaker diarization'), ('policy', 'Auto-applied by policy'), ('transcript_word', 'Picked from transcript')], default='manual', max_length=20)),
                ('applied_by_policy_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('label', models.CharField(blank=True, help_text='Optional human label, e.g. "blur CEO 0:32"', max_length=120)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_face_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.faceidentity')),
                ('target_speaker_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='videos.speakeridentity')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redactions', to='videos.video')),
            ],
            options={
                'ordering': ['video', 'time_start_s'],
                'indexes': [models.Index(fields=['video', 'time_start_s'], name='videos_reda_video_i_eb8cd5_idx'), models.Index(fields=['target_type'], name='videos_reda_target__2e3a7b_idx'), models.Index(fields=['applied_by_policy_id'], name='videos_reda_applied_01dd37_idx')],
            },
        ),
    ]
