# Generated by Django 4.2.16 on 2026-06-04 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0052_video_redacted_raw_blocked_redaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactionRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=15)),
                ('file_path', models.CharField(blank=True, help_text='Path under MEDIA_ROOT, e.g. "redacted/uuid__ts.mp4"', max_length=600)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('duration_s', models.FloatField(default=0)),
                ('redaction_count', models.PositiveIntegerField(default=0, help_text='How many Redaction rows were baked in')),
                ('included_redaction_ids', models.JSONField(blank=True, default=list, help_text='Snapshot of Redaction PKs at render time')),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional automatic-cleanup date', null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('rendered_by_username', models.CharField(blank=True, max_length=150)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redaction_renders', to='videos.video')),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['video', '-queued_at'], name='videos_reda_video_i_d1f9dc_idx'), models.Index(fields=['status'], name='videos_reda_status_8aeb59_idx')],
            },
        ),
    ]
