# Generated by Django 4.2.16 on 2026-06-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0053_redactionrender'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaction',
            name='is_saved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='redaction',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
