# Generated by Django 4.2.16 on 2026-06-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0054_redaction_is_saved_redaction_saved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosegment',
            name='redacted_original_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
