# Generated by Django 4.2.16 on 2026-06-05 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0055_videosegment_redacted_original_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human label, e.g. "Blur Riya — HR request 2026-06"', max_length=140)),
                ('description', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('face', 'Face identity'), ('voice', 'Voice / speaker identity')], max_length=20)),
                ('visual_method', models.CharField(default='black_box', help_text='black_box for now (the only reliable option)', max_length=20)),
                ('visual_severity', models.CharField(default='heavy', max_length=10)),
                ('audio_method', models.CharField(blank=True, default='', help_text='mute | beep | <empty> = no audio redaction', max_length=20)),
                ('redact_transcripts', models.BooleanField(default=True, help_text='Also rewrite VideoSegment.text for matched ranges')),
                ('true_erasure', models.BooleanField(default=False, help_text='Do NOT keep originals (no reversibility). GDPR mode.')),
                ('apply_to_existing', models.BooleanField(default=True)),
                ('apply_to_future', models.BooleanField(default=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by_username', models.CharField(blank=True, max_length=150)),
                ('last_applied_at', models.DateTimeField(blank=True, null=True)),
                ('affected_videos_count', models.PositiveIntegerField(default=0)),
                ('auto_created_redactions', models.PositiveIntegerField(default=0)),
                ('target_face_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redaction_policies', to='videos.faceidentity')),
                ('target_speaker_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redaction_policies', to='videos.speakeridentity')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['active', '-created_at'], name='videos_reda_active_0613c4_idx'), models.Index(fields=['target_face_identity'], name='videos_reda_target__d1fc67_idx'), models.Index(fields=['target_speaker_identity'], name='videos_reda_target__699466_idx')],
            },
        ),
    ]
