# Generated by Django 4.2.16 on 2026-06-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0056_redactionpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='redaction',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redactions', to='videos.photo'),
        ),
        migrations.AddField(
            model_name='redactionrender',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redaction_renders', to='videos.photo'),
        ),
        migrations.AlterField(
            model_name='redaction',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redactions', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='redactionrender',
            name='file_path',
            field=models.CharField(blank=True, help_text='Storage-form path (tenants/<slug>/redacted/<uuid>__<ts>.<ext>)', max_length=600),
        ),
        migrations.AlterField(
            model_name='redactionrender',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redaction_renders', to='videos.video'),
        ),
        migrations.AddIndex(
            model_name='redaction',
            index=models.Index(fields=['photo'], name='videos_reda_photo_i_a53803_idx'),
        ),
        migrations.AddIndex(
            model_name='redactionrender',
            index=models.Index(fields=['photo', '-queued_at'], name='videos_reda_photo_i_538dfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='redaction',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('photo__isnull', True), ('video__isnull', False)), models.Q(('photo__isnull', False), ('video__isnull', True)), _connector='OR'), name='redaction_video_xor_photo'),
        ),
        migrations.AddConstraint(
            model_name='redactionrender',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('photo__isnull', True), ('video__isnull', False)), models.Q(('photo__isnull', False), ('video__isnull', True)), _connector='OR'), name='redactionrender_video_xor_photo'),
        ),
    ]
