# Generated by Django 4.2.16 on 2026-06-08 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0057_redaction_photo_redactionrender_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inapp_upload_complete', models.BooleanField(default=True)),
                ('inapp_upload_failed', models.BooleanField(default=True)),
                ('inapp_photo_complete', models.BooleanField(default=True)),
                ('inapp_photo_failed', models.BooleanField(default=True)),
                ('inapp_quota_warnings', models.BooleanField(default=True)),
                ('email_upload_complete', models.BooleanField(default=False, help_text='Most users find one email per upload noisy — off by default.')),
                ('email_upload_failed', models.BooleanField(default=True)),
                ('email_photo_complete', models.BooleanField(default=False)),
                ('email_photo_failed', models.BooleanField(default=True)),
                ('email_quota_warnings', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videos.photo'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, help_text='Short bell-display title; falls back to message if empty', max_length=160),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('mention', 'Mention'), ('comment', 'Comment on your video'), ('reply', 'Reply to your comment'), ('subscribe', 'New subscriber'), ('new_video', 'New video'), ('upload_complete', 'Upload processed'), ('upload_failed', 'Upload failed'), ('photo_complete', 'Photo processed'), ('photo_failed', 'Photo processing failed'), ('quota_80', 'Quota warning (80%)'), ('quota_95', 'Quota critical (95%)')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type', '-created_at'], name='notif_recipient_type'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
