# Generated by Django 4.2.16 on 2026-05-29 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_username', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='usageevent',
            new_name='tenants_usa_tenant__765251_idx',
            old_name='tenants_usa_tenant__idx',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Chosen by org admin during onboarding', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.plan'),
        ),
        migrations.AddField(
            model_name='onboardinginvite',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='tenants.tenant'),
        ),
    ]
