# Generated by Django 4.2.16 on 2026-05-29 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_onboardinginvite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gb_amount', models.PositiveIntegerField(help_text='Extra GB added per month')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='If set, addon is no longer active', null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_addons', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AICreditPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_purchased', models.PositiveIntegerField()),
                ('minutes_consumed', models.FloatField(default=0, help_text='Drained as overage accrues; updated lazily by metering')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=120)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_packs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['purchased_at'],
            },
        ),
    ]
