# Generated by Django 4.2.16 on 2026-05-29 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_storageaddon_aicreditpack'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('storage', 'Storage Addon (monthly)'), ('credits', 'AI Credit Pack (one-time)')], max_length=20)),
                ('name', models.CharField(help_text="Public display name, e.g. '500 GB Pack'", max_length=100)),
                ('amount', models.PositiveIntegerField(help_text='Number of GB (for storage) or minutes (for credits)')),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Hide from the org top-up page when unchecked')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('stripe_price_id', models.CharField(blank=True, default='', max_length=120)),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'amount'],
            },
        ),
        migrations.AddField(
            model_name='aicreditpack',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price snapshot at purchase time', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='storageaddon',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price snapshot at subscription time', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='aicreditpack',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_packs', to='tenants.topupproduct'),
        ),
        migrations.AddField(
            model_name='storageaddon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_addons', to='tenants.topupproduct'),
        ),
    ]
