# Generated by Django 4.2.16 on 2026-05-29 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_topupproduct_aicreditpack_price_usd_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['price_usd', 'name']},
        ),
        migrations.AddField(
            model_name='plan',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly price. 0 = free.', max_digits=8),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan_status',
            field=models.CharField(choices=[('none', 'No subscription'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete (awaiting payment)')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_plan_subscription_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
