# Generated by Django 4.2.16 on 2026-05-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_plan_options_plan_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageaddon',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the subscription actually terminates (end of paid period). Null = renews indefinitely.', null=True),
        ),
        migrations.AlterField(
            model_name='storageaddon',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the user requested cancellation. Storage is still granted until expires_at.', null=True),
        ),
    ]
