# Generated by Django 4.2.16 on 2026-05-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_storageaddon_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('interest', models.CharField(blank=True, help_text="e.g. 'Pro plan', 'Enterprise', 'Demo'", max_length=80)),
                ('message', models.TextField(blank=True)),
                ('referrer', models.CharField(blank=True, default='', max_length=300)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
