# Generated by Django 4.2.16 on 2026-05-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_leadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='feature_audio_events',
            field=models.BooleanField(default=True, help_text='PANNs audio event detection (applause, music, silence).'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='feature_auto_captions',
            field=models.BooleanField(default=True, help_text='Auto-trigger caption generation after upload.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='feature_clip_embeddings',
            field=models.BooleanField(default=True, help_text='CLIP semantic search embeddings on frames + photos.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='feature_diarization',
            field=models.BooleanField(default=True, help_text='pyannote speaker diarization. Biometric — GDPR-sensitive.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='feature_face_recognition',
            field=models.BooleanField(default=True, help_text='Run InsightFace on uploaded media. Biometric — GDPR-sensitive.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='feature_object_detection',
            field=models.BooleanField(default=True, help_text='YOLO object labels on frames.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='feature_scene_description',
            field=models.BooleanField(default=True, help_text='BLIP/Florence-2 natural language frame descriptions.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='feature_speech_to_text',
            field=models.BooleanField(default=True, help_text='Whisper transcription for video audio tracks.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='feature_translation',
            field=models.BooleanField(default=True, help_text='NLLB-200 translation of subtitles into other languages.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='feature_video_summary',
            field=models.BooleanField(default=True, help_text='Ollama-based AI video summary (no-op if USE_OLLAMA=false).'),
        ),
    ]
