# Generated by Django 4.2.16 on 2026-05-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_tenant_feature_audio_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='hls_enabled_qualities',
            field=models.CharField(blank=True, default='', help_text="Comma-separated list of HLS heights to encode for new uploads, e.g. '1080,720,480'. Empty = use global HLS_QUALITIES setting.", max_length=120),
        ),
        migrations.AddField(
            model_name='tenant',
            name='hls_multi_quality',
            field=models.BooleanField(default=True, help_text='If False, encode only a single rendition (no adaptive streaming). Saves AI minutes and disk space.'),
        ),
    ]
