# Generated by Django 4.2.16 on 2026-05-31 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_hls_enabled_qualities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('tenant', 'Tenant')], db_index=True, max_length=10)),
                ('name', models.CharField(help_text="Friendly label, e.g. 'SendGrid prod'.", max_length=80)),
                ('host', models.CharField(max_length=200)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False, help_text='Mutually exclusive with TLS. SMTPS on port 465.')),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password_enc', models.BinaryField(blank=True, default=b'', help_text='Fernet-encrypted SMTP password.')),
                ('from_email', models.EmailField(help_text="The 'From:' address used for sent emails.", max_length=254)),
                ('from_name', models.CharField(blank=True, default='', help_text="Optional display name, e.g. 'ClipLens'.", max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Only one connection per scope is active at a time.')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_result', models.CharField(blank=True, default='', help_text="'OK' on success, otherwise the error message.", max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('tenant', models.ForeignKey(blank=True, help_text="Required when scope='tenant'.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_connections', to='tenants.tenant')),
            ],
            options={
                'ordering': ['scope', '-is_active', 'name'],
                'indexes': [models.Index(fields=['scope', 'is_active'], name='tenants_ema_scope_aae77f_idx'), models.Index(fields=['tenant', 'is_active'], name='tenants_ema_tenant__f3d317_idx')],
            },
        ),
    ]
