# Generated by Django 4.2.16 on 2026-05-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_emailconnection'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('platform', 'Platform'), ('tenant', 'Tenant')], max_length=10)),
                ('connection_name_snapshot', models.CharField(blank=True, help_text='Name of the connection at send time (preserved if connection deleted)', max_length=120)),
                ('backend_type', models.CharField(choices=[('smtp', 'SMTP (managed)'), ('console', 'Console (dev mode)'), ('default', 'Django default'), ('disabled', 'Disabled (dropped)')], default='smtp', max_length=12)),
                ('subject', models.CharField(max_length=300)),
                ('from_email', models.CharField(blank=True, max_length=320)),
                ('to_emails', models.JSONField(default=list, help_text='List of recipient addresses')),
                ('cc_emails', models.JSONField(blank=True, default=list)),
                ('bcc_emails', models.JSONField(blank=True, default=list)),
                ('reply_to', models.CharField(blank=True, max_length=320)),
                ('body_preview', models.CharField(blank=True, help_text='First 500 chars of plain body', max_length=500)),
                ('has_html', models.BooleanField(default=False)),
                ('template_key', models.CharField(blank=True, help_text='Future: template system key', max_length=64)),
                ('trigger_source', models.CharField(blank=True, help_text='What code path queued this — e.g. submit_lead, create_tenant, quota_warning, manual_test', max_length=64)),
                ('triggered_by_username', models.CharField(blank=True, help_text='Username of the human who initiated (blank = system / webhook)', max_length=150)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('dropped', 'Dropped')], db_index=True, default='queued', max_length=10)),
                ('error_class', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Time spent in the send call (ms)', null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=64)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='tenants.emailconnection')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['scope', 'queued_at'], name='tenants_ema_scope_3bab3e_idx'), models.Index(fields=['tenant', 'queued_at'], name='tenants_ema_tenant__30ef4b_idx'), models.Index(fields=['status', 'queued_at'], name='tenants_ema_status_24c7ab_idx'), models.Index(fields=['trigger_source'], name='tenants_ema_trigger_38cb7b_idx')],
            },
        ),
    ]
