# Generated by Django 4.2.16 on 2026-06-01 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Initial description of the issue')),
                ('category', models.CharField(choices=[('bug', 'Bug / something broken'), ('billing', 'Billing / subscription'), ('feature_request', 'Feature request'), ('question', 'How-to / question'), ('other', 'Other')], default='question', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_on_user', 'Waiting on User'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('created_by_username', models.CharField(blank=True, max_length=150)),
                ('created_by_email', models.CharField(blank=True, max_length=320)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author_username', models.CharField(blank=True, max_length=150)),
                ('author_role', models.CharField(choices=[('tenant', 'Tenant'), ('platform', 'Platform')], max_length=10)),
                ('is_internal', models.BooleanField(default=False, help_text='Internal note — only visible to platform staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tenants.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['tenant', 'status', '-updated_at'], name='tenants_sup_tenant__21fad7_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'priority', '-updated_at'], name='tenants_sup_status_0f90b4_idx'),
        ),
    ]
