# Generated by Django 4.2.16 on 2026-06-01 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_supportticket_supportmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(blank=True, max_length=320)),
                ('role', models.CharField(choices=[('superadmin', 'Superadmin'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=20)),
                ('invited_by_username', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invites', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'consumed_at'], name='tenants_tea_tenant__ccdb24_idx'), models.Index(fields=['token'], name='tenants_tea_token_e6d9b8_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='teammemberinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True)), fields=('tenant', 'username'), name='unique_pending_invite_per_tenant_username'),
        ),
    ]
