# Generated by Django 4.2.16 on 2026-06-05 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_plan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='media_relocating',
            field=models.BooleanField(default=False, help_text='True while a media-relocation Celery task is running. Blocks tenant access via maintenance page.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='media_relocation_cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='media_relocation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='media_relocation_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='media_root_absolute',
            field=models.CharField(blank=True, default='', help_text="Optional absolute path for this tenant's media. Must be already mounted and writable. Leave blank for default.", max_length=500),
        ),
        migrations.CreateModel(
            name='MediaRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=600)),
                ('target_path', models.CharField(max_length=600)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('verifying', 'Verifying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=20)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('bytes_copied', models.BigIntegerField(default=0)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('files_copied', models.PositiveIntegerField(default=0)),
                ('old_path_soft_deleted', models.CharField(blank=True, default='', help_text='Where the old data is parked until grace period expires', max_length=600)),
                ('grace_period_until', models.DateTimeField(blank=True, null=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by_username', models.CharField(blank=True, max_length=150)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_relocations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-queued_at'],
                'indexes': [models.Index(fields=['tenant', '-queued_at'], name='tenants_med_tenant__856e6e_idx'), models.Index(fields=['status', '-queued_at'], name='tenants_med_status_74f23e_idx')],
            },
        ),
    ]
