# Generated by Django 4.2.16 on 2026-06-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_tenant_media_relocating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=200)),
                ('task_id', models.CharField(blank=True, default='', max_length=64)),
                ('tenant_slug', models.CharField(blank=True, db_index=True, default='', help_text='Empty for non-tenant (platform) tasks', max_length=100)),
                ('queue', models.CharField(blank=True, default='', max_length=50)),
                ('args_snippet', models.TextField(blank=True, default='', help_text='Truncated repr of task args for debugging')),
                ('error_message', models.TextField(blank=True, default='')),
                ('traceback', models.TextField(blank=True, default='', help_text='Truncated to last 8000 chars')),
                ('failed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by_username', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'ordering': ['-failed_at'],
                'indexes': [models.Index(fields=['resolved', '-failed_at'], name='tenants_fai_resolve_58da7b_idx'), models.Index(fields=['tenant_slug', '-failed_at'], name='tenants_fai_tenant__c11976_idx')],
            },
        ),
    ]
