# Generated by Django 4.2.16 on 2026-06-25 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_failedtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='max_videos',
        ),
    ]
