# Generated by Django 4.2.16 on 2026-07-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_remove_max_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardinginvite',
            name='source',
            field=models.CharField(choices=[('self_service', 'Self-service signup'), ('admin', 'Admin-provisioned')], default='admin', max_length=20),
        ),
    ]
